// ══════════════════════════════════════════════
//   DZESPORTS — main.js
//   Generated by Admin Tool — 2026-03-09
// ══════════════════════════════════════════════

const CONFIG = {
  "brand": {
    "name": "DZESPORTS",
    "tagline": "Players Above All",
    "description": "Building an Esport Ecosystem where players come first.",
    "about": "Our goal is to bridge the gap between just playing and professional esports by providing a top-tier competitive environment backed by high-quality production. We don't just host matches — we create a broadcast-level experience where teams can showcase their talent the way it was meant to be seen. Algeria has incredible talent. DZESPORTS exists to give that talent the platform, the structure, and the spotlight it deserves.",
    "founded": "2024",
    "country": "Algeria"
  },
  "logos": {
    "main": "data/main.png",
    "valorant": "data/valo.png",
    "lol": "data/lol.png",
    "rocketleague": "data/rl.png",
    "r6": "data/r6.png",
    "cs2": "data/cs.png"
  },
  "colors": {
    "bg": "#060810",
    "bg2": "#0a0d16",
    "bg3": "#0f1320",
    "surface": "#111827",
    "surface2": "#1a2234",
    "border": "#1e2d45",
    "text": "#e8eaf0",
    "textDim": "#8896aa",
    "accent": "#00f5d4",
    "games": {
      "valorant": "#ff4655",
      "lol": "#fed557",
      "rocketleague": "#55badd",
      "r6": "#a0a0a0",
      "cs2": "#fbac26"
    }
  },
  "socials": {
    "discord": "https://discord.gg/MFzXh9UkGM",
    "twitter": "YOUR_TWITTER_LINK",
    "twitch": "https://www.twitch.tv/esports_algeria",
    "youtube": "YOUR_YOUTUBE_LINK",
    "instagram": "https://www.instagram.com/esports.algeria/",
    "email": "contact@dzesports.gg",
    "discordServerId": "814983580534964224"
  },
  "stats": {
    "games": "5",
    "tournaments": "9+",
    "players": "400+",
    "community": "1300"
  },
  "media": [
    {
      "type": "twitch",
      "label": "HOUSSAM",
      "src": "https://www.twitch.tv/esports_algeria/clip/EntertainingTrustworthyWatercressGivePLZ-w8gGRIh1XdlagAkf",
      "game": "r6",
      "caption": "Tournament Highlight"
    },
    {
      "type": "video",
      "label": "IFC 2025 EDIT",
      "src": "https://i.imgur.com/wNB5Wzi.mp4",
      "game": "lol",
      "caption": "Tournament Highlight"
    },
    {
      "type": "image",
      "label": "Image1",
      "src": "https://i.imgur.com/Ty1H1Eu.jpeg",
      "game": "valorant",
      "caption": "IFC2025 Valorant"
    },
    {
      "type": "image",
      "label": "Image2",
      "src": "https://i.imgur.com/n0ywxxX.jpeg",
      "game": "lol",
      "caption": "IFC2025 League of Legends"
    },
    {
      "type": "image",
      "label": "Image3",
      "src": "https://i.imgur.com/BuE25HZ.jpeg",
      "game": "general",
      "caption": "IFC2025 League of Legends"
    },
    {
      "type": "image",
      "label": "Image4",
      "src": "https://i.imgur.com/9Mw5m3D.jpeg",
      "game": "lol",
      "caption": "IFC2025 League of Legends"
    }
  ]
};

const TOURNAMENTS = [
  {
    "id": "ascention-cup",
    "game": "valorant",
    "name": "ASCENTION CUP",
    "status": "completed",
    "date": "2025-12-20",
    "prize": "-",
    "teams": "8",
    "format": "Single Elimination",
    "banner": "https://i.imgur.com/IP0aAKe.png",
    "bracketUrl": "",
    "champion": "1024 ESPORTS",
    "mvp": "GREEN"
  },
  {
    "id": "dzlol-community-cup",
    "game": "lol",
    "name": "DZLOL COMMUNITY CUP",
    "status": "completed",
    "date": "2025-05-20",
    "prize": "125$",
    "teams": "16",
    "format": "Swiss + Playoffs",
    "banner": "https://i.imgur.com/WAeNVWM.png",
    "bracketUrl": "",
    "champion": "ARABIK ANANZ",
    "mvp": "Sayn"
  },
  {
    "id": "dzlol-champions-arena",
    "game": "lol",
    "name": "DZLOL CHAMPIONS ARENA",
    "status": "completed",
    "date": "2025-06-06",
    "prize": "-",
    "teams": "16",
    "format": "Group Stage + Playoffs",
    "banner": "https://i.imgur.com/ZFE8Qq7.png",
    "bracketUrl": "",
    "champion": "RaoOuf + Nail",
    "mvp": ""
  },
  {
    "id": "ifa-constantine-2025",
    "game": "lol",
    "name": "IFA CONSTANTINE 2025",
    "status": "completed",
    "date": "2025-10-03",
    "prize": "300,000DZD + INTERNATIONAL TOURNAMENT",
    "teams": "16",
    "format": "Double Elimination",
    "banner": "https://i.imgur.com/9bRMffI.png",
    "bracketUrl": "",
    "champion": "DPL ESPORTS",
    "mvp": ""
  },
  {
    "id": "dzramadan-champions-arena---rl",
    "game": "rocketleague",
    "name": "DZRAMADAN CHAMPIONS ARENA - RL",
    "status": "completed",
    "date": "2026-02-22",
    "prize": "-",
    "teams": "8",
    "format": "Double Elimination",
    "banner": "https://i.imgur.com/hqUZBel.png",
    "bracketUrl": "",
    "champion": "NightWatch",
    "mvp": "Specter"
  },
  {
    "id": "dzramadan-champions-arena---r6",
    "game": "r6",
    "name": "DZRAMADAN CHAMPIONS ARENA - R6",
    "status": "completed",
    "date": "2026-02-26",
    "prize": "-",
    "teams": "8",
    "format": "Single Elimination",
    "banner": "https://i.imgur.com/qZLVhk1.png",
    "bracketUrl": "",
    "champion": "Team Kiwi",
    "mvp": "Gomezz"
  },
  {
    "id": "dzramadan-champions-arena---lol",
    "game": "lol",
    "name": "DZRAMADAN CHAMPIONS ARENA - LOL",
    "status": "upcoming",
    "date": "2026-03-12",
    "prize": "50 Hextech Chests",
    "teams": "32",
    "format": "Single Elimination",
    "banner": "https://i.imgur.com/7XJShrk.png",
    "bracketUrl": "",
    "champion": "",
    "mvp": ""
  }
];

const NEWS = [
  {
    "id": "launch",
    "featured": true,
    "tag": "Announcement",
    "game": "general",
    "title": "DZESPORTS Officially Launches — Algeria's New Esports Hub",
    "excerpt": "We're excited to announce the official launch of DZESPORTS — a broadcast-quality competitive platform built for Algerian players across 5 titles. Players Above All.",
    "date": "2025",
    "image": "https://i.imgur.com/y1xgmyV.png"
  },
  {
    "id": "team-kiwi-wins-the-dzramadan-champions-t",
    "featured": false,
    "tag": "Rainbow Six Siege",
    "game": "r6",
    "title": "TEAM KIWI Wins the DZRamadan Champions Tour",
    "excerpt": "",
    "date": "March 3rd",
    "image": "https://i.imgur.com/REtZBXN.png"
  },
  {
    "id": "nightwatch-claim-the-victory",
    "featured": false,
    "tag": "Rocket League",
    "game": "rocketleague",
    "title": "NIGHTWATCH Claim the Victory",
    "excerpt": "",
    "date": "FEB 26",
    "image": "https://i.imgur.com/JIcy5ch.png"
  }
];

const CHAMPIONS = [
  {
    "id": "champ-1773023347974",
    "game": "lol",
    "winner": "DPL ESPORTS",
    "title": "IFA CONSTANTINE 2025",
    "subtitle": "",
    "date": "Oct 3, 2025",
    "prize": "300,000 DZD",
    "image": "data/DPL.png",
    "banner": "https://i.imgur.com/9bRMffI.png",
    "pending": false
  }
];

const PARTNERS = [
  {
    "id": "partner-1772926233096",
    "name": "IFC CONSTANTINE",
    "logo": "data/logo_ifa.png",
    "url": "",
    "tier": "gold",
    "visible": true
  },
  {
    "id": "partner-1772929435905",
    "name": "NOVACORE",
    "logo": "data/Logo_4.png",
    "url": "",
    "tier": "standard",
    "visible": true
  },
  {
    "id": "partner-1772932090066",
    "name": "DEFENDR",
    "logo": "data/defendr.png",
    "url": "https://defendr.gg/",
    "tier": "standard",
    "visible": true
  },
  {
    "id": "partner-1772932372122",
    "name": "DA3AMNI",
    "logo": "data/da3amni.png",
    "url": "https://www.da3amni.com/",
    "tier": "standard",
    "visible": true
  },
  {
    "id": "partner-1772932447698",
    "name": "6GPA",
    "logo": "data/6GPA.png",
    "url": "",
    "tier": "standard",
    "visible": true
  },
  {
    "id": "partner-1772995351863",
    "name": "Della3",
    "logo": "data/della3.png",
    "url": "",
    "tier": "silver",
    "visible": true
  }
];

const SVG_ICONS = {
  discord: `<svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20"><path d="M20.317 4.37a19.791 19.791 0 00-4.885-1.515.074.074 0 00-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 00-5.487 0 12.64 12.64 0 00-.617-1.25.077.077 0 00-.079-.037A19.736 19.736 0 003.677 4.37a.07.07 0 00-.032.027C.533 9.046-.32 13.58.099 18.057a.082.082 0 00.031.057 19.9 19.9 0 005.993 3.03.078.078 0 00.084-.028c.462-.63.874-1.295 1.226-1.994a.076.076 0 00-.041-.106 13.107 13.107 0 01-1.872-.892.077.077 0 01-.008-.128 10.2 10.2 0 00.372-.292.074.074 0 01.077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 01.078.01c.12.098.246.198.373.292a.077.077 0 01-.006.127 12.299 12.299 0 01-1.873.892.077.077 0 00-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 00.084.028 19.839 19.839 0 006.002-3.03.077.077 0 00.032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 00-.031-.03z"/></svg>`,
  twitter: `<svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.744l7.73-8.835L1.254 2.25H8.08l4.253 5.622zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>`,
  twitch:  `<svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20"><path d="M11.571 4.714h1.715v5.143H11.57zm4.715 0H18v5.143h-1.714zM6 0L1.714 4.286v15.428h5.143V24l4.286-4.286h3.428L22.286 12V0zm14.571 11.143l-3.428 3.428h-3.429l-3 3v-3H6.857V1.714h13.714z"/></svg>`,
  youtube: `<svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20"><path d="M23.498 6.186a3.016 3.016 0 00-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 00.502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 002.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 002.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>`,
  instagram:`<svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z"/></svg>`,
  email:   `<svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20"><path d="M20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/></svg>`
};

// ── INIT: CSS VARS ──
function injectCSSVars() {
  const r = document.documentElement.style;
  const c = CONFIG.colors;
  r.setProperty('--bg',       c.bg);
  r.setProperty('--bg2',      c.bg2);
  r.setProperty('--bg3',      c.bg3);
  r.setProperty('--surface',  c.surface);
  r.setProperty('--surface2', c.surface2);
  r.setProperty('--border',   c.border);
  r.setProperty('--text',     c.text);
  r.setProperty('--text-dim', c.textDim);
  r.setProperty('--cyan',     c.accent);
  r.setProperty('--white',    '#ffffff');
  r.setProperty('--val',      c.games.valorant);
  r.setProperty('--lol',      c.games.lol);
  r.setProperty('--rl',       c.games.rocketleague);
  r.setProperty('--r6',       c.games.r6);
  r.setProperty('--cs',       c.games.cs2);
  r.setProperty('--font-display', "'Exo 2', sans-serif");
  r.setProperty('--font-ui',     "'Rajdhani', sans-serif");
  r.setProperty('--font-mono',   "'Share Tech Mono', monospace");
  document.querySelectorAll('[data-game]').forEach(el => {
    const g = el.dataset.game;
    if (CONFIG.colors.games[g]) el.style.setProperty('--game-color', CONFIG.colors.games[g]);
  });
}

const TRANSPARENT_PX = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';
function injectLogos() {
  document.querySelectorAll('[data-logo]').forEach(img => {
    const key = img.dataset.logo;
    img.src = CONFIG.logos[key] || TRANSPARENT_PX;
  });
}

const _PH = ['YOUR_TWITTER_LINK','YOUR_YOUTUBE_LINK','YOUR_DISCORD_LINK','YOUR_TWITCH_LINK','YOUR_INSTAGRAM_LINK'];
function _isPH(v) { return !v || v === '#' || _PH.includes(v); }

function injectSocials() {
  document.querySelectorAll('[data-social]').forEach(el => {
    const key = el.dataset.social;
    let href = CONFIG.socials[key] || '#';
    if (key === 'email' && href !== '#') href = 'mailto:' + href;
    el.href = _isPH(CONFIG.socials[key]) ? '#' : href;
  });
  document.querySelectorAll('.social-card[data-social]').forEach(el => {
    const key = el.dataset.social;
    const iconEl = el.querySelector('.social-icon');
    if (iconEl && SVG_ICONS[key]) iconEl.innerHTML = SVG_ICONS[key];
    if (_isPH(CONFIG.socials[key])) {
      el.style.opacity='0.3'; el.style.pointerEvents='none'; el.title='Coming soon';
      const lbl=el.querySelector('.social-card-label'); if(lbl) lbl.textContent='Coming soon';
    }
  });
  document.querySelectorAll('.footer-links a[data-social], #mobileNavOverlay a[data-social]').forEach(el => {
    if (_isPH(CONFIG.socials[el.dataset.social])) el.style.display='none';
  });
  const navDiscord = document.querySelector('.nav-cta a[data-social="discord"]');
  if (navDiscord) {
    const existing = navDiscord.innerHTML;
    navDiscord.innerHTML = SVG_ICONS.discord + '<span>' + (existing.trim() || 'JOIN DISCORD') + '</span>';
    navDiscord.style.display = 'inline-flex';
    navDiscord.style.alignItems = 'center';
    navDiscord.style.gap = '8px';
  }
}

function hexToRgb(hex) {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return r ? `${parseInt(r[1],16)},${parseInt(r[2],16)},${parseInt(r[3],16)}` : '0,245,212';
}

function renderHero() {
  const set = (id, html) => { const el = document.getElementById(id); if (el) el.innerHTML = html; };
  const setText = (id, txt) => { const el = document.getElementById(id); if (el) el.textContent = txt; };
  set('heroEyebrow', "// Algeria's Premier Esports Organization");
  set('heroTitle', '<span class="dz">DZ</span><span class="es">ESPORTS</span>');
  set('heroTagline', '— ' + CONFIG.brand.tagline + ' —');
  setText('heroDesc', CONFIG.brand.description);
  setText('navBrandName', CONFIG.brand.name);
  setText('footerBrandName', CONFIG.brand.name);
  setText('footerBrandDesc', CONFIG.brand.description);
  setText('footerCopy', '© ' + CONFIG.brand.founded + ' ' + CONFIG.brand.name + '. All rights reserved.');
  setText('footerTagline', '// ' + CONFIG.brand.tagline);
  setText('aboutText', CONFIG.brand.about);
  setText('aboutFounded', CONFIG.brand.founded);
  setText('aboutCountry', CONFIG.brand.country);
  setText('aboutTagline', CONFIG.brand.tagline);
}

function parseTourDate(d) {
  if (!d || d === 'TBD') return 0;
  const s = d.trim();
  const iso = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return new Date(iso[1], iso[2]-1, iso[3]).getTime();
  const dmy = s.match(/^(\d{2})\/(\d{2})\/(\d{4})/);
  if (dmy) return new Date(dmy[3], dmy[2]-1, dmy[1]).getTime();
  return 0;
}
function formatTourDate(d) {
  if (!d || d === 'TBD') return 'TBD';
  const s = d.trim();
  const iso = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return iso[3] + '/' + iso[2] + '/' + iso[1];
  if (s.match(/^\d{2}\/\d{2}\/\d{4}/)) return s;
  return s;
}
function renderTournaments(filter = 'all') {
  const grid = document.getElementById('tourGrid');
  if (!grid) return;
  const raw = filter === 'all' ? TOURNAMENTS : TOURNAMENTS.filter(t => t.game === filter);
  const items = [...raw].sort((a, b) => parseTourDate(b.date) - parseTourDate(a.date));
  if (!items.length) { grid.innerHTML = '<div class="empty-state" style="grid-column:1/-1">// No tournaments announced yet — check back soon</div>'; return; }
  grid.innerHTML = items.map(t => {
    const gc = CONFIG.colors.games[t.game] || CONFIG.colors.accent;
    const statusClass = { live:'status-live', upcoming:'status-upcoming', completed:'status-completed' }[t.status] || 'status-upcoming';
    const statusLabel = { live:'● LIVE', upcoming:'UPCOMING', completed:'COMPLETED' }[t.status] || 'UPCOMING';
    const gameName = { valorant:'Valorant', lol:'League of Legends', rocketleague:'Rocket League', r6:'Rainbow Six Siege', cs2:'Counter-Strike 2' }[t.game] || t.game;
    let bannerContent;
    if (t.banner) { bannerContent = '<img class="tour-banner-img" src="' + t.banner + '" alt="' + t.name + '" loading="lazy">'; }
    else if (CONFIG.logos[t.game]) { bannerContent = '<img data-logo="' + t.game + '" class="tour-banner-logo" alt="' + gameName + '">'; }
    else { bannerContent = '<div class="tour-banner-generated" style="background:linear-gradient(135deg,' + gc + '22,' + gc + '44);"><span class="tour-banner-watermark" style="color:' + gc + '">' + gameName + '</span></div>'; }
    const championStrip = (t.status === 'completed' && t.champion)
      ? '<div class="tour-champion-strip"><div class="tour-champion-name">🏆 CHAMPION: ' + t.champion + '</div>' + (t.mvp ? '<div class="tour-mvp-name">⭐ MVP: ' + t.mvp + '</div>' : '') + '</div>' : '';
    const bracketBtn = t.bracketUrl ? '<a href="' + t.bracketUrl + '" target="_blank" rel="noopener" class="tour-bracket-btn">View Bracket →</a>' : '';
    const cdId = 'cd-' + t.id;
    const cdHTML = (t.status === 'upcoming' && t.date && t.date !== 'TBD') ? '<div class="tour-countdown" id="' + cdId + '" style="display:flex;gap:6px;align-items:center;margin:10px 0 6px;"></div>' : '';
    return '<div class="tour-card reveal" data-game="' + t.game + '" style="--game-color:' + gc + '"><div class="tour-banner">' + bannerContent + championStrip + '</div><div class="tour-body"><div class="tour-status-row"><span class="game-badge" style="--game-color:' + gc + '">' + gameName + '</span><span class="status-badge ' + statusClass + '">' + statusLabel + '</span></div><div class="tour-name">' + t.name + '</div>' + cdHTML + '<div class="tour-meta"><div class="tour-meta-item"><span class="tour-meta-label">Date</span><span class="tour-meta-value">' + formatTourDate(t.date) + '</span></div><div class="tour-meta-item"><span class="tour-meta-label">Prize Pool</span><span class="tour-meta-value">' + t.prize + '</span></div><div class="tour-meta-item"><span class="tour-meta-label">Teams</span><span class="tour-meta-value">' + t.teams + '</span></div><div class="tour-meta-item"><span class="tour-meta-label">Format</span><span class="tour-meta-value">' + t.format + '</span></div></div>' + bracketBtn + '</div></div>';
  }).join('');
  injectLogos();
  grid.querySelectorAll('[data-game]').forEach(el => { const g = el.dataset.game; if (CONFIG.colors.games[g]) el.style.setProperty('--game-color', CONFIG.colors.games[g]); });
  reObserveReveals(grid);
  items.forEach(t => {
    if (t.status !== 'upcoming' || !t.date || t.date === 'TBD') return;
    const cdEl = document.getElementById('cd-' + t.id);
    if (!cdEl) return;
    const target = new Date(t.date + 'T20:00:00').getTime();
    function pad(n) { return String(n).padStart(2,'0'); }
    function unit(v,l) { return '<div style="text-align:center;min-width:34px"><div style="color:var(--cyan);font-family:var(--font-mono);font-size:.9rem;font-weight:700">'+pad(v)+'</div><div style="color:var(--text-dim);font-family:var(--font-mono);font-size:.5rem;letter-spacing:.1em">'+l+'</div></div>'; }
    function sep() { return '<div style="color:var(--border);font-family:var(--font-mono);padding-bottom:10px">:</div>'; }
    function tick() {
      if (!document.getElementById('cd-' + t.id)) return;
      const diff = target - Date.now();
      if (diff <= 0) { cdEl.innerHTML = '<span style="color:var(--cyan);font-family:var(--font-mono);font-size:.75rem;letter-spacing:.15em">● LIVE NOW</span>'; return; }
      const d=Math.floor(diff/86400000),h=Math.floor((diff%86400000)/3600000),m=Math.floor((diff%3600000)/60000),s=Math.floor((diff%60000)/1000);
      cdEl.innerHTML = unit(d,'DAYS')+sep()+unit(h,'HRS')+sep()+unit(m,'MIN')+sep()+unit(s,'SEC');
      setTimeout(tick,1000);
    }
    tick();
  });
  document.querySelectorAll('.filter-btn').forEach(btn => { btn.onclick = () => { document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active')); btn.classList.add('active'); renderTournaments(btn.dataset.filter); }; });
}

function renderNews() {
  const grid = document.getElementById('newsGrid');
  if (!grid) return;
  if (!NEWS.length) { grid.innerHTML = '<div class="empty-state" style="grid-column:1/-1">No news posted yet — check back soon</div>'; return; }
  const featured = NEWS.find(n => n.featured) || NEWS[0];
  const rest = NEWS.filter(n => n !== featured);
  const gc = CONFIG.colors.games[featured.game] || CONFIG.colors.accent;
  const featuredHTML = '<div class="news-featured reveal"><div class="news-featured-banner">' + (featured.image ? '<img src="' + featured.image + '" alt="' + featured.title + '" loading="lazy">' : '<span class="news-banner-placeholder">ADD_FEATURED_IMAGE</span>') + '</div><div class="news-featured-body"><span class="news-tag" style="background:rgba(' + hexToRgb(gc) + ',.1);color:' + gc + ';border-color:rgba(' + hexToRgb(gc) + ',.3)">' + featured.tag + '</span><div class="news-featured-title">' + featured.title + '</div>' + (featured.excerpt ? '<div class="news-featured-excerpt">' + featured.excerpt + '</div>' : '') + '<div class="news-featured-date">' + featured.date + '</div></div></div>';
  const listHTML = '<div class="news-list">' + rest.map(n => { const ic = CONFIG.colors.games[n.game] || CONFIG.colors.accent; return '<div class="news-item reveal" style="--item-color:' + ic + '"><span class="news-item-tag">' + n.tag + '</span><div class="news-item-title">' + n.title + '</div><div class="news-item-date">' + n.date + '</div></div>'; }).join('') + '</div>';
  grid.innerHTML = featuredHTML + listHTML;
  reObserveReveals(grid);
}

function renderChampions() {
  const grid = document.getElementById('championsGrid');
  if (!grid) return;
  if (!CHAMPIONS.length) { grid.innerHTML = '<div class="empty-state" style="grid-column:1/-1">No champions yet</div>'; return; }
  const gameLabels = { valorant:'Valorant', lol:'League of Legends', rocketleague:'Rocket League', r6:'Rainbow Six Siege', cs2:'Counter-Strike 2', general:'General' };
  grid.innerHTML = CHAMPIONS.map(c => {
    const gc = CONFIG.colors.games[c.game] || CONFIG.colors.accent;
    const pending = c.pending || c.winner === 'TBD' || !c.winner;
    const bannerImgHTML = c.banner
      ? '<img src="' + c.banner + '" class="hof-banner-img" alt="" loading="lazy">'
      : '<div class="hof-banner-fallback" style="background:linear-gradient(135deg,' + gc + '33 0%,var(--surface2) 100%)"></div>';
    const imgHTML = c.image
      ? '<div class="hof-img-wrap"><img src="' + c.image + '" alt="' + c.winner + '" class="hof-img"></div>'
      : '<div class="hof-img-wrap hof-img-placeholder"><span class="hof-placeholder-icon">' + (pending ? '🔒' : '🏆') + '</span></div>';
    return '<div class="hof-card reveal' + (pending ? ' hof-pending' : '') + '" style="--game-color:' + gc + '">'
      + '<div class="hof-banner">' + bannerImgHTML + '<div class="hof-banner-overlay"></div>'
      + '<span class="hof-game-tag">' + (gameLabels[c.game]||c.game) + '</span>'
      + (c.prize ? '<span class="hof-prize">🏅 ' + c.prize + '</span>' : '')
      + imgHTML + '</div>'
      + '<div class="hof-body"><div class="hof-winner">' + (c.winner||'TBD') + '</div>'
      + (c.subtitle ? '<div class="hof-subtitle">' + c.subtitle + '</div>' : '')
      + '<div class="hof-title">' + c.title + '</div>'
      + (c.date ? '<div class="hof-date">' + c.date + '</div>' : '')
      + '</div><div class="hof-glow" style="background:radial-gradient(circle at 50% 0%,' + gc + '33 0%,transparent 70%)"></div></div>';
  }).join('');
  reObserveReveals(grid);
}

function renderPartners() {
  const container = document.getElementById('partnersContainer');
  if (!container) return;
  const visible = PARTNERS.filter(p => p.visible !== false);
  if (!visible.length) {
    container.innerHTML = '<div class="partners-band"><div class="partners-stage"><div class="partners-empty">Partners Announced Soon</div></div></div>';
    return;
  }
  container.innerHTML = '<div class="partners-band"><div class="partners-header">TRUSTED BY</div><div class="partners-stage"></div></div>';
  const stage = container.querySelector('.partners-stage');
  const tierColors = { gold:'#fbbf24', silver:'#94a3b8', bronze:'#cd7f32' };
  const SPEED = 0.7;
  const SLOT = 240;
  const PADDING = 60;
  function makeEl(p, slotX) {
    const tc = tierColors[p.tier] || '';
    const dotStyle = tc ? 'background:' + tc + ';box-shadow:0 0 6px ' + tc : 'background:var(--border)';
    const inner = p.logo ? '<img class="partner-logo" src="' + p.logo + '" alt="' + p.name + '" loading="lazy">' : '<span class="partner-name-fallback">' + p.name + '</span>';
    const el = document.createElement('a');
    el.className = 'partner-item tier-' + (p.tier || 'standard');
    el.href = p.url || '#'; el.target = p.url ? '_blank' : '_self'; el.rel = 'noopener'; el.title = p.name;
    el.style.cssText = '--partner-color:' + (tc||'var(--border)') + ';position:absolute;top:0;width:' + SLOT + 'px;left:' + slotX + 'px;padding:0 ' + PADDING + 'px;box-sizing:border-box';
    el.innerHTML = '<div class="partner-tier-dot" style="' + dotStyle + '"></div>' + inner;
    return el;
  }
  const stageW = stage.offsetWidth || window.innerWidth;
  let items = [], nextX = stageW, poolIdx = 0;
  function spawn() {
    const p = visible[poolIdx % visible.length]; poolIdx++;
    const el = makeEl(p, nextX);
    stage.appendChild(el);
    items.push({ el, x: nextX });
    nextX += SLOT;
  }
  while (nextX < stageW + SLOT * 2) spawn();
  function tick() {
    nextX -= SPEED;
    for (let i = 0; i < items.length; i++) { items[i].x -= SPEED; items[i].el.style.left = items[i].x + 'px'; }
    if (items.length && items[0].x + SLOT < 0) { items[0].el.remove(); items.shift(); }
    if (nextX <= stageW + SLOT) spawn();
    requestAnimationFrame(tick);
  }
  requestAnimationFrame(tick);
}
function getYouTubeId(src) {
  if (!src) return '';
  const m = src.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([^&?\/\s]{11})/);
  return m ? m[1] : src;
}
function getTwitchSlug(src) {
  if (!src) return '';
  const m = src.match(/(?:clips\.twitch\.tv\/|twitch\.tv\/[^\/]+\/clip\/)([^\/?&]+)/);
  return m ? m[1] : src;
}

function renderMedia() {
  const grid = document.getElementById('mediaGrid');
  if (!grid) return;
  const items = CONFIG.media;
  if (!items.length) { grid.innerHTML = '<div class="empty-state" style="grid-column:1/-1">No media yet</div>'; return; }
  grid.innerHTML = items.map((m, i) => {
    const gc = CONFIG.colors.games[m.game] || CONFIG.colors.accent;
    const isFirst = i === 0;
    let content;
    if (m.type === 'youtube' && m.src) {
      const vid = getYouTubeId(m.src);
      content = '<div class="media-iframe-wrap"><iframe src="https://www.youtube.com/embed/' + vid + '" frameborder="0" allowfullscreen allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy"></iframe></div>';
    } else if (m.type === 'twitch' && m.src) {
      const slug = getTwitchSlug(m.src);
      const host = location.hostname ? location.hostname : 'localhost';
      const embedSrc = 'https://clips.twitch.tv/embed?clip=' + encodeURIComponent(slug) + '&parent=' + host + '&autoplay=false';
      content = '<div class="media-iframe-wrap"><iframe src="' + embedSrc + '" frameborder="0" allowfullscreen scrolling="no" allow="autoplay; fullscreen" loading="lazy"></iframe></div>';
    } else if (m.type === 'video' && m.src) {
      content = '<div class="media-iframe-wrap"><video src="' + m.src + '" controls preload="metadata" style="width:100%;height:100%;object-fit:cover"></video></div>';
    } else if (m.src) {
      content = '<img src="' + m.src + '" alt="' + m.caption + '" loading="lazy">';
    } else {
      content = '<div class="media-placeholder"><div class="media-placeholder-bar" style="background:' + gc + '"></div><div class="media-placeholder-label">' + m.label + '</div><div class="media-placeholder-bar" style="background:' + gc + '"></div></div>';
    }
    const spanStyle = isFirst ? 'grid-column:span 2;grid-row:span 2;' : '';
    return '<div class="media-cell reveal" style="' + spanStyle + '--game-color:' + gc + '">' + content + '<div class="media-overlay"><span class="media-expand">⊕</span></div><div class="media-caption">' + m.caption + '</div></div>';
  }).join('');
  reObserveReveals(grid);
}

function renderStats() {
  const el = document.getElementById('heroStats');
  if (!el) return;
  const labels = { games:'Games', tournaments:'Tournaments Hosted', players:'Players Competing', community:'Community Members' };
  el.innerHTML = Object.entries(CONFIG.stats).map(([k, v]) => '<div class="stat-item"><span class="stat-num" data-target="' + v + '">' + v + '</span><span class="stat-label">' + labels[k] + '</span></div>').join('');
}

function initDiscordWidget() {
  const widgetContainer = document.getElementById('discordWidgetContainer');
  if (!widgetContainer) return;
  const sid = CONFIG.socials.discordServerId;
  const discordUrl = CONFIG.socials.discord || '#';
  const fallbackMembers = CONFIG.stats.community || '0';

  function statusColor(s) {
    return s === 'online' ? '#23d160' : s === 'idle' ? '#f5a623' : s === 'dnd' ? '#f87171' : '#4b5563';
  }

  function renderWidget(data) {
    const serverName = data ? data.name : 'DZESPORTS';
    const members = data ? (data.members || []) : [];
    const onlineCount = data ? (data.presence_count ?? members.length) : null;
    const totalMembers = parseInt(fallbackMembers);

    const membersHTML = members.length
      ? members.map(m => {
          const avatarUrl = m.avatar_url || '';
          const status = (m.status || 'online');
          const activity = m.game ? `<span class="dc-member-activity">${m.game.name}</span>` : '';
          const avatarEl = avatarUrl
            ? `<img src="${avatarUrl}" alt="${m.username}" class="dc-member-avatar">`
            : `<div class="dc-member-avatar dc-member-initials">${(m.username||'?')[0].toUpperCase()}</div>`;
          return `<div class="dc-member">
            <div class="dc-member-avatar-wrap">
              ${avatarEl}
              <span class="dc-member-status" style="background:${statusColor(status)};box-shadow:0 0 5px ${statusColor(status)}"></span>
            </div>
            <div class="dc-member-info">
              <span class="dc-member-name">${m.username}</span>
              ${activity}
            </div>
          </div>`;
        }).join('')
      : '<div class="dc-empty">No members visible right now.</div>';

    widgetContainer.innerHTML = `
      <div class="discord-widget">
        <div class="discord-header">
          ${SVG_ICONS.discord}
          <div>
            <div class="discord-server-name">${serverName}</div>
            <div class="discord-online">
              ${onlineCount !== null ? `<span class="discord-dot"></span> ${onlineCount} Online` : 'Discord Community'}
            </div>
          </div>
          <div class="discord-total-badge">
            <span class="discord-total-num">${totalMembers.toLocaleString()}</span>
            <span class="discord-total-label">Members</span>
          </div>
        </div>
        <div class="dc-members-list">${membersHTML}</div>
        <div class="discord-footer">
          <a href="${discordUrl}" target="_blank" rel="noopener" class="discord-join-btn">${SVG_ICONS.discord} JOIN SERVER</a>
        </div>
      </div>`;
  }

  const isReal = sid && sid !== 'YOUR_SERVER_ID';
  if (isReal) {
    fetch('https://discord.com/api/guilds/' + sid + '/widget.json')
      .then(r => { if (!r.ok) throw new Error('Widget fetch failed'); return r.json(); })
      .then(data => renderWidget(data))
      .catch(() => renderWidget(null));
  } else {
    renderWidget(null);
  }
}

function initNav() {
  const nav = document.getElementById('mainNav');
  window.addEventListener('scroll', () => { nav.classList.toggle('scrolled', window.scrollY > 50); }, { passive: true });
  const sections = document.querySelectorAll('section[id]');
  const navLinks = document.querySelectorAll('.nav-links a, #mobileNavOverlay a');
  const sectionObserver = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const id = entry.target.id;
        navLinks.forEach(a => { a.classList.toggle('active', a.getAttribute('href') === '#' + id); });
        const titles = { home:'DZESPORTS — Home', games:'DZESPORTS — Games', tournaments:'DZESPORTS — Tournaments', champions:'DZESPORTS — Hall of Fame', news:'DZESPORTS — News', media:'DZESPORTS — Media', about:'DZESPORTS — About', community:'DZESPORTS — Community', contact:'DZESPORTS — Contact' };
        document.title = titles[id] || 'DZESPORTS — ' + CONFIG.brand.tagline;
      }
    });
  }, { threshold: 0.4 });
  sections.forEach(s => sectionObserver.observe(s));
  const hamburger = document.getElementById('hamburger');
  const overlay = document.getElementById('mobileNavOverlay');
  const mobileLinks = overlay ? overlay.querySelectorAll('a') : [];
  function openMobileNav() { hamburger.classList.add('open'); overlay.classList.add('open'); document.body.style.overflow = 'hidden'; mobileLinks.forEach((a,i) => { a.style.animationDelay = i*50 + 'ms'; }); }
  function closeMobileNav() { hamburger.classList.remove('open'); overlay.classList.remove('open'); document.body.style.overflow = ''; }
  if (hamburger) hamburger.addEventListener('click', () => { hamburger.classList.contains('open') ? closeMobileNav() : openMobileNav(); });
  mobileLinks.forEach(a => a.addEventListener('click', closeMobileNav));
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', e => {
      const target = document.querySelector(anchor.getAttribute('href'));
      if (!target) return;
      e.preventDefault();
      window.scrollTo({ top: target.getBoundingClientRect().top + window.scrollY - 80, behavior: 'smooth' });
    });
  });
  document.querySelectorAll('.footer-game-logo').forEach(img => {
    const game = img.dataset.logo;
    if (!game || game === 'main') return;
    const anchor = img.closest('a') || img.parentElement;
    if (anchor && anchor.tagName === 'A') {
      anchor.href = '#tournaments';
      anchor.addEventListener('click', () => {
        setTimeout(() => {
          document.querySelectorAll('.filter-btn').forEach(btn => { btn.classList.toggle('active', btn.dataset.filter === game); });
          renderTournaments(game);
        }, 400);
      });
    }
  });
}

const revealObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      const siblings = entry.target.parentElement.querySelectorAll('.reveal');
      let delay = 0;
      siblings.forEach((sib,idx) => { if (sib === entry.target) delay = idx * 80; });
      setTimeout(() => entry.target.classList.add('visible'), Math.min(delay, 600));
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.08 });

function initScrollReveal() { document.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el)); }
function reObserveReveals(container) { container.querySelectorAll('.reveal').forEach(el => { el.classList.remove('visible'); revealObserver.observe(el); }); }

function initStatCounter() {
  const statsEl = document.getElementById('heroStats');
  if (!statsEl) return;
  let animated = false;
  const counterObserver = new IntersectionObserver(entries => {
    if (entries[0].isIntersecting && !animated) {
      animated = true; counterObserver.disconnect();
      statsEl.querySelectorAll('.stat-num').forEach(el => {
        const target = el.dataset.target;
        if (isNaN(target)) return;
        const duration = 1200, start = performance.now(), num = parseFloat(target);
        function step(now) { const t = Math.min((now-start)/duration,1), ease = 1-Math.pow(1-t,3); el.textContent = Math.floor(ease*num).toLocaleString(); if (t<1) requestAnimationFrame(step); else el.textContent = target; }
        requestAnimationFrame(step);
      });
    }
  }, { threshold: 0.4 });
  counterObserver.observe(statsEl);
}

function initContactForm() {
  const form = document.getElementById('contactForm');
  if (!form) return;
  form.addEventListener('submit', e => { e.preventDefault(); const success = document.getElementById('formSuccess'); if (success) { success.style.display='block'; form.reset(); } setTimeout(() => { if (success) success.style.display='none'; }, 5000); });
}

function initBackToTop() {
  const btn = document.getElementById('backToTop');
  if (!btn) return;
  window.addEventListener('scroll', () => { btn.classList.toggle('visible', window.scrollY > 400); }, { passive: true });
  btn.addEventListener('click', () => { window.scrollTo({ top: 0, behavior: 'smooth' }); });
}

function initParticleCanvas() {
  const canvas = document.getElementById('heroParticles');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  let particles = [];
  function resize() { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; }
  resize();
  window.addEventListener('resize', resize);
  const cyan = CONFIG.colors.accent || '#00f5d4';
  for (let i = 0; i < 60; i++) { particles.push({ x: Math.random()*canvas.width, y: Math.random()*canvas.height, r: Math.random()*1.5+0.5, vx: (Math.random()-.5)*.3, vy: (Math.random()-.5)*.3 }); }
  function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    particles.forEach(p => { ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, Math.PI*2); ctx.fillStyle = cyan + '1a'; ctx.fill(); p.x += p.vx; p.y += p.vy; if (p.x<0) p.x=canvas.width; if (p.x>canvas.width) p.x=0; if (p.y<0) p.y=canvas.height; if (p.y>canvas.height) p.y=0; });
    requestAnimationFrame(draw);
  }
  draw();
}

function initNewsletter() {
  const form = document.getElementById('newsletterForm');
  if (!form) return;
  form.addEventListener('submit', e => { e.preventDefault(); const msg = document.getElementById('newsletterMsg'); if (msg) { msg.style.display='block'; form.querySelector('input').value=''; } });
}

function initScrollProgress() {
  if (document.getElementById('dzScrollProgress')) return;
  const bar = document.createElement('div');
  bar.id = 'dzScrollProgress';
  bar.style.cssText = 'position:fixed;top:0;left:0;height:2px;width:0%;background:linear-gradient(90deg,var(--cyan),rgba(255,255,255,.4));box-shadow:0 0 8px var(--cyan);z-index:99999;pointer-events:none;';
  document.body.appendChild(bar);
  window.addEventListener('scroll', () => {
    const h = document.documentElement.scrollHeight - window.innerHeight;
    bar.style.width = (h > 0 ? (window.scrollY / h) * 100 : 0) + '%';
  }, { passive: true });
}

document.addEventListener('DOMContentLoaded', () => {
  injectCSSVars();
  injectLogos();
  injectSocials();
  renderHero();
  renderTournaments('all');
  renderNews();
  renderChampions();
  renderPartners();
  renderMedia();
  renderStats();
  initNav();
  initScrollReveal();
  initStatCounter();
  initDiscordWidget();
  initContactForm();
  initBackToTop();
  initParticleCanvas();
  initNewsletter();
  initScrollProgress();
  const loader = document.getElementById('pageLoader');
  if (loader) { setTimeout(() => { loader.classList.add('fade-out'); setTimeout(() => loader.remove(), 400); }, 300); }
});
